apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: kavindasandamal/backendappv1/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb+srv://kavindasandamal:1234@cluster0.3a2hmte.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
